version: '3.8'

services: 
  postgres:
    image: postgres:15
    container_name: postgresContainer
    restart: always
    environment: 
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    
    ports:
      - "5432:5432"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
    driver: local

